In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from numpy import inf
from scipy.linalg import norm
%matplotlib inline

In [4]:
vec_1 = np.array([1,2,3])
vec_2 = np.array([3,2,1])
print(vec_1, vec_2)

[1 2 3] [3 2 1]


In [5]:
vec_sum = np.add(vec_1,vec_2)
vec_sum

array([4, 4, 4])

In [6]:
vec_diff = np.subtract(vec_1,vec_2)
vec_diff

array([-2,  0,  2])

In [7]:
vec_ans = np.add(2*vec_diff,vec_sum)
vec_ans

array([0, 4, 8])

In [10]:
vec_1 = np.array([3,4,12])
l1_norm = norm(vec_1, 1)
l2_norm = norm(vec_1, 2)
lmax_norm = norm(vec_1, inf)
unit_vector = np.multiply(1/l2_norm, vec_1)
print(l1_norm, l2_norm, lmax_norm, unit_vector)

19.0 13.0 12.0 [0.23076923 0.30769231 0.92307692]
