In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report,confusion_matrix
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [4]:
path = r"Data\spambase.csv"

In [5]:
df = pd.read_csv(path)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 58 columns):
0         4600 non-null float64
0.64      4600 non-null float64
0.64.1    4600 non-null float64
0.1       4600 non-null float64
0.32      4600 non-null float64
0.2       4600 non-null float64
0.3       4600 non-null float64
0.4       4600 non-null float64
0.5       4600 non-null float64
0.6       4600 non-null float64
0.7       4600 non-null float64
0.64.2    4600 non-null float64
0.8       4600 non-null float64
0.9       4600 non-null float64
0.10      4600 non-null float64
0.32.1    4600 non-null float64
0.11      4600 non-null float64
1.29      4600 non-null float64
1.93      4600 non-null float64
0.12      4600 non-null float64
0.96      4600 non-null float64
0.13      4600 non-null float64
0.14      4600 non-null float64
0.15      4600 non-null float64
0.16      4600 non-null float64
0.17      4600 non-null float64
0.18      4600 non-null float64
0.19      4600 non-null float

In [6]:
df.describe()

0         0.64       0.64.1          0.1         0.32  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      0.104576     0.212922     0.280578     0.065439     0.312222   
std       0.305387     1.290700     0.504170     1.395303     0.672586   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.420000     0.000000     0.382500   
max       4.540000    14.280000     5.100000    42.810000    10.000000   

               0.2          0.3          0.4          0.5          0.6  ...  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000  ...   
mean      0.095922     0.114233     0.105317     0.090087     0.239465  ...   
std       0.273850     0.391480     0.401112     0.278643     0.644816  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.160000  ...   
max       5.880000     7.270000    11.110000     5.260000    18.180000  ...   

              0.40         0.41         0.42        0.778         0.43  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      0.038583     0.139061     0.016980     0.268960     0.075827   
std       0.243497     0.270377     0.109406     0.815726     0.245906   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.065000     0.000000     0.000000     0.000000   
75%       0.000000     0.188000     0.000000     0.314250     0.052000   
max       4.385000     9.752000     4.081000    32.478000     6.003000   

              0.44        3.756           61           278            1  
count  4600.000000  4600.000000  4600.000000   4600.000000  4600.000000  
mean      0.044248     5.191827    52.170870    283.290435     0.393913  
std       0.429388    31.732891   194.912453    606.413764     0.488669  
min       0.000000     1.000000     1.000000      1.000000     0.000000  
25%       0.000000     1.588000     6.000000     35.000000     0.000000  
50%       0.000000     2.275500    15.000000     95.000000     0.000000  
75%       0.000000     3.705250    43.000000    265.250000     1.000000  
max      19.829000  1102.500000  9989.000000  15841.000000     1.000000  

[8 rows x 58 columns]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns="1", axis=1), df["1"], random_state=0, test_size=0.2)

In [12]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
y_pred = lr.predict(X_test)

In [15]:
score = lr.score(X_test, y_test)
score

0.9380434782608695

In [16]:
class_report = classification_report(y_test, y_pred)
class_report

'              precision    recall  f1-score   support\n\n           0       0.94      0.95      0.95       538\n           1       0.93      0.92      0.93       382\n\n    accuracy                           0.94       920\n   macro avg       0.94      0.94      0.94       920\nweighted avg       0.94      0.94      0.94       920\n'

In [17]:
confu_mat = confusion_matrix(y_test, y_pred)
confu_mat

array([[511,  27],
       [ 30, 352]], dtype=int64)

In [18]:
df1 = df.copy()

In [23]:
df1_corr = df1.corr().unstack()
df1_corr[(abs(df1_corr)>0.75) & (abs(df1_corr)!=1)]

0.23  0.25    0.996066
      0.31    0.848020
0.25  0.23    0.996066
      0.31    0.845358
0.31  0.23    0.848020
      0.25    0.845358
dtype: float64

In [24]:
df1 = df1.drop(columns=["0.25", "0.31"])
df1.columns

Index(['0', '0.64', '0.64.1', '0.1', '0.32', '0.2', '0.3', '0.4', '0.5', '0.6',
       '0.7', '0.64.2', '0.8', '0.9', '0.10', '0.32.1', '0.11', '1.29', '1.93',
       '0.12', '0.96', '0.13', '0.14', '0.15', '0.16', '0.17', '0.18', '0.19',
       '0.20', '0.21', '0.22', '0.23', '0.24', '0.26', '0.27', '0.28', '0.29',
       '0.30', '0.32.2', '0.33', '0.34', '0.35', '0.36', '0.37', '0.38',
       '0.39', '0.40', '0.41', '0.42', '0.778', '0.43', '0.44', '3.756', '61',
       '278', '1'],
      dtype='object')

In [27]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df1.drop(columns="1", axis=1), df1["1"], random_state=0, test_size=0.2)

In [29]:
lr1 = LogisticRegression()
lr1.fit(X_train1, y_train1)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
score1 = lr1.score(X_test1, y_test1)
print(score1)

0.933695652173913


In [32]:
y_pred1 = lr1.predict(X_test1)
class_report1 = classification_report(y_test1, y_pred1)
print(class_report1)

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       538
           1       0.92      0.92      0.92       382

    accuracy                           0.93       920
   macro avg       0.93      0.93      0.93       920
weighted avg       0.93      0.93      0.93       920



In [33]:
confu_mat1 = confusion_matrix(y_test1, y_pred1)
print(confu_mat1)

[[508  30]
 [ 31 351]]


In [34]:
chi2(X_train1, y_train1)

(array([4.92989686e+01, 2.40099470e+01, 1.32276537e+02, 4.01387987e+02,
        3.34165751e+02, 1.38741461e+02, 5.34348060e+02, 2.19653623e+02,
        1.73623936e+02, 1.37460103e+02, 1.34269716e+02, 6.19027243e-01,
        7.40914030e+01, 2.19248485e+01, 1.98016607e+02, 7.47857655e+02,
        3.44802261e+02, 2.47446597e+02, 5.25954098e+02, 3.79385418e+02,
        9.13450339e+02, 2.75519583e+02, 4.92990959e+02, 3.78472345e+02,
        1.14900622e+03, 5.76823537e+02, 1.76289778e+03, 1.95192305e+02,
        2.07610255e+02, 1.99145302e+02, 1.41001808e+02, 9.62926373e+01,
        1.67691153e+02, 1.94968193e+02, 9.30856711e+01, 1.30848536e+02,
        1.73427991e+01, 1.20841748e+02, 1.10501308e+02, 2.91966248e+02,
        6.88747254e+01, 1.47822666e+02, 2.65351394e+02, 3.74211088e+02,
        7.67582954e+00, 6.77017573e+01, 1.34060200e+01, 1.44730716e+01,
        8.96314500e+00, 5.03087839e+02, 3.06685795e+02, 5.06719388e+01,
        9.41796345e+03, 1.16237822e+05, 2.76657249e+05]),
 array