In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.linalg import norm
from numpy import inf
import math
import scipy
%matplotlib inline

In [3]:
vec_1 = np.array([1,2,3])
vec_2 = np.array([3,2,1])

In [4]:
vec_sum = np.add(vec_1,vec_2)
vec_diff = np.subtract(vec_1,vec_2)
vec_ans = np.add(2*vec_diff,vec_sum)

In [5]:
print(vec_sum, vec_diff, vec_ans)

[4 4 4] [-2  0  2] [0 4 8]


In [6]:
vec_1 = np.array([3,4,12])
l1_norm = norm(vec_1, 1)
l2_norm = norm(vec_1, 2)

In [7]:
lmax_norm = norm(vec_1, inf)
unit_vector = np.multiply(1/l2_norm, vec_1)
print(l1_norm, l2_norm, lmax_norm, unit_vector)

19.0 13.0 12.0 [0.23076923 0.30769231 0.92307692]


In [8]:
vec_1 * vec_2

array([ 9,  8, 12])

In [9]:
np.cross(vec_1, vec_2)

array([-20,  33,  -6])

In [10]:
np.dot(vec_1, vec_2)

29

In [11]:
vec_1 = np.array([1,1,1])
vec_2 = np.array([2,2,1])

In [12]:
vec_dot = np.dot(vec_1, vec_2)
vec_cross = np.cross(vec_1, vec_2)

In [13]:
print(vec_dot, vec_cross)

5 [-1  1  0]


In [14]:
np.dot(np.array([7,-4,-1]), np.array([8, -5, 6]))

70

In [15]:
vec_1 = np.array([1,2,2])
vec_2 = np.array([6,0,-3])

In [16]:
dp_1 = np.dot(vec_1, vec_2)
orthog = 1 if dp_1==0 else 0
u1_n = vec_1/np.linalg.norm(vec_1)
u2_n = vec_2/np.linalg.norm(vec_2)
dp_2 = np.dot(u1_n, u2_n)
orthon = 1 if dp_2==0 else 0
print(orthog, orthon)

1 1


In [17]:
print(u1_n, u2_n, dp_2)

[0.33333333 0.66666667 0.66666667] [ 0.89442719  0.         -0.4472136 ] 0.0


In [18]:
vec_1 = np.array([1,1,0])
vec_2 = np.array([1,0,1])
vec_3= np.array([0,1,1])
vec = np.array([1,1,1])
proj_vec_1 = round(np.dot(vec, vec_1)/(norm(vec_1)**2),2)
proj_vec_2 = round(np.dot(vec, vec_2)/(norm(vec_2)**2),2)
proj_vec_3 = round(np.dot(vec, vec_3)/(norm(vec_3)**2),2)
vec_new = [proj_vec_1, proj_vec_2, proj_vec_3]
vec_new

[1.0, 1.0, 1.0]

In [19]:
np.cross(np.array([1,2,3]), np.array([2,1,-2]))

array([-7,  8, -3])

In [20]:
mat_1 = np.array([[1,1,1],[2,2,2],[3,3,3]])
mat_2 = np.array([[0,0,1],[0,0,1],[0,0,1]])
mat_sum = mat_1+mat_2
mat_sum

array([[1, 1, 2],
       [2, 2, 3],
       [3, 3, 4]])

In [21]:
mat_1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
mat_2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
mat_prod = np.matmul(mat_1, mat_2)
mat_prod

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
mat_1 = np.array([[7,2,1],[0,-3,-1],[-3,4,-2]])
mat_1

array([[ 7,  2,  1],
       [ 0, -3, -1],
       [-3,  4, -2]])

In [23]:
mat_t = mat_1.T
mat_t

array([[ 7,  0, -3],
       [ 2, -3,  4],
       [ 1, -1, -2]])

In [24]:
mat_det = scipy.linalg.det(mat_1)
mat_det

67.0

In [25]:
mat_inv = 0 if mat_det==0 else np.linalg.inv(mat_1)
mat_inv

array([[ 0.14925373,  0.11940299,  0.01492537],
       [ 0.04477612, -0.1641791 ,  0.10447761],
       [-0.13432836, -0.50746269, -0.31343284]])

In [26]:
np.matmul(np.array([[2,-3],[4,-7]]),np.linalg.inv(np.array([[2,-3],[4,-7]])))

array([[1., 0.],
       [0., 1.]])

In [27]:
sum=0
for i in [1,2,3,4,5,6,7,8,9]:
    sum = sum + i**2
sum**0.5

16.881943016134134

In [28]:
mat_1 = np.array([[1,0,0],[0,0,1],[0,1,0]])
mat_1

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [29]:
mat_t = mat_1.T
mat_inv = np.linalg.inv(mat_1)
print(mat_t, mat_inv, sep="\n")

[[1 0 0]
 [0 0 1]
 [0 1 0]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [30]:
ortho = (mat_t==mat_inv).all()
ortho

True

In [31]:
mat_1 = np.array([[-0.60587,0.79556],[0.79556,0.60587]])
print((mat_1.T==np.linalg.inv(mat_1)).all())
print(np.matmul(mat_1,mat_1.T))
print(round(np.linalg.det(mat_1)))
print(mat_1.T)
print(np.linalg.inv(mat_1))

False
[[ 9.99994171e-01 -2.46400347e-17]
 [-2.46400347e-17  9.99994171e-01]]
-1.0
[[-0.60587  0.79556]
 [ 0.79556  0.60587]]
[[-0.60587353  0.79556464]
 [ 0.79556464  0.60587353]]


In [32]:
mat_1 = np.array([[-3,-4],[4,6],[1,1]])
mat_2 = np.array([[0,-1/2,3],[0,1/2,-2]])
print(mat_1, mat_2, sep='\n')

[[-3 -4]
 [ 4  6]
 [ 1  1]]
[[ 0.  -0.5  3. ]
 [ 0.   0.5 -2. ]]


In [33]:
mat_prod=np.matmul(mat_2, mat_1)
mat_prod

array([[1., 0.],
       [0., 1.]])

In [34]:
mat_1 = np.array([[1,2,-16],[2,1,4],[2,-2,1]])
np.linalg.det(mat_1)

117.00000000000003

In [35]:
mat_1 = np.array([[2,0,0,0,0],[0,3,0,0,0],[0,0,4,0,0],[0,0,0,2,0],[0,0,0,0,2]])
mat_mul = np.matmul(np.matmul(mat_1, mat_1),mat_1)
mat_mul

array([[ 8,  0,  0,  0,  0],
       [ 0, 27,  0,  0,  0],
       [ 0,  0, 64,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  8]])

In [36]:
2**3

8

In [37]:
mat_1 = np.array([[-0.68567,0.14807,0.71269],[0.12975,0.93855,-0.31982],[-0.71626,0.31176,0.62433]])
print(np.linalg.det(mat_1.T))
print(mat_1.T.T)
print(np.linalg.inv(mat_1.T))

0.05971142371011999
[[-0.68567  0.14807  0.71269]
 [ 0.12975  0.93855 -0.31982]
 [-0.71626  0.31176  0.62433]]
[[ 11.4830959    2.47971739  11.93568397]
 [  2.17284538   1.37975254   1.80380661]
 [-11.99520799  -2.12387252 -11.09917701]]


In [38]:
mat_1 = np.array([[1,0,1],[1,0,1],[1,0,1]])
values,vectors = np.linalg.eig(mat_1)
lhs = np.matmul(mat_1,vectors[:,1])
print(lhs)
rhs = vectors[:,1]*values[1]
print(rhs)

[1.15470054 1.15470054 1.15470054]
[1.15470054 1.15470054 1.15470054]


In [39]:
vectors

array([[ 0.        ,  0.57735027, -0.70710678],
       [ 1.        ,  0.57735027,  0.        ],
       [ 0.        ,  0.57735027,  0.70710678]])

In [40]:
values

array([0., 2., 0.])

In [41]:
mat_1 = np.array([[0,1],[-2,-3]])
values,vectors = np.linalg.eig(mat_1)
values, vectors

(array([-1., -2.]), array([[ 0.70710678, -0.4472136 ],
        [-0.70710678,  0.89442719]]))

In [42]:
mat_2 = np.array([[1,2],[2,1]])
u,s,vt = np.linalg.svd(mat_2)
print(u,s,vt,sep='\n')

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[3. 1.]
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [43]:
mat = np.array([[3,1,1],[-1,3,1]])
np.matmul(mat,mat.T)

array([[11,  1],
       [ 1, 11]])

In [44]:
mat = np.array([[1,0],[1,2]])
values,vectors = np.linalg.eig(mat)
values

array([2., 1.])

# Assignment

In [51]:
adj_mat = np.array([[0,0,0,0,0,0,1/3,0],
                   [1/2,0,1/2,1/3,0,0,0,0],
                   [1/2,0,0,0,0,0,0,0],
                   [0,1,0,0,0,0,0,0],
                  [0,0,1/2,1/3,0,0,1/3,0],
                   [0,0,0,1/3,1/3,0,0,1/2],
                   [0,0,0,0,1/3,0,0,1/2],
                   [0,0,0,0,1/3,1,1/3,0]])
adj_mat

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33333333, 0.        ],
       [0.5       , 0.        , 0.5       , 0.33333333, 0.        ,
        0.        , 0.        , 0.        ],
       [0.5       , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.33333333, 0.        ,
        0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.        , 0.33333333, 0.33333333,
        0.        , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 0.        , 0.33333333,
        0.        , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 0.        , 0.33333333,
        1.        , 0.33333333, 0.        ]])

In [46]:
eigenvalues, eigenvectors = np.linalg.eig(adj_mat)
eigen_1 = abs(eigenvectors[:,0])/np.linalg.norm(eigenvectors[:,0],1)
eigen_1

array([0.06  , 0.0675, 0.03  , 0.0675, 0.0975, 0.2025, 0.18  , 0.295 ])

In [47]:
page = np.where(eigen_1==eigen_1.max())[0][0]+1
page

8

In [48]:
abs(eigenvectors[:,0])

array([0.14004708, 0.15755296, 0.07002354, 0.15755296, 0.2275765 ,
       0.47265889, 0.42014124, 0.68856481])

In [49]:
0.15/2.3

0.06521739130434782

In [92]:
init_I = [1,0,0,0,0,0,0,0]
for i in range(10):
    init_I = np.dot(adj_mat,init_I)
power_page = np.argmax(init_I)+1
init_I

array([0.06730348, 0.06450046, 0.02690615, 0.07000171, 0.10489779,
       0.18293229, 0.16304203, 0.3204161 ])

In [105]:
init_I = [1,0,0,0,0,0,0,0]
for i in range(10):
    init_I = np.dot(adj_mat,init_I)
    init_I /= np.linalg.norm(init_I,1)
init_I

array([0.06730348, 0.06450046, 0.02690615, 0.07000171, 0.10489779,
       0.18293229, 0.16304203, 0.3204161 ])

In [72]:
new_adj_mat = np.array([[0,0,0,0,0,0,0,0],
                   [1/2,0,1/2,1/3,0,0,0,0],
                  [1/2,0,0,0,0,0,0,0],
                   [0,1,0,0,0,0,0,0],
                   [0,0,1/2,1/3,0,0,1/2,0],
                   [0,0,0,1/3,1/3,0,0,1/2],
                   [0,0,0,0,1/3,0,0,1/2],
                   [0,0,0,0,1/3,1,1/2,0]])

In [109]:
new_init_I = np.array([1,0,0,0,0,0,0,0])
for i in range(10):
    new_init_I = np.dot(new_adj_mat, new_init_I)
    new_init_I /= np.linalg.norm(new_init_I,1)
new_init_I

array([0.        , 0.00308642, 0.        , 0.00617284, 0.13327064,
       0.21433738, 0.21125096, 0.43188175])

In [117]:
alpha = 0.85
n = len(new_adj_mat)
G = (alpha * new_adj_mat) + (((1 - alpha) * (1/n)) * np.ones(new_adj_mat.shape))
n, G

(8, array([[0.01875   , 0.01875   , 0.01875   , 0.01875   , 0.01875   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.44375   , 0.01875   , 0.44375   , 0.30208333, 0.01875   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.44375   , 0.01875   , 0.01875   , 0.01875   , 0.01875   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.01875   , 0.86875   , 0.01875   , 0.01875   , 0.01875   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.01875   , 0.01875   , 0.44375   , 0.30208333, 0.01875   ,
         0.01875   , 0.44375   , 0.01875   ],
        [0.01875   , 0.01875   , 0.01875   , 0.30208333, 0.30208333,
         0.01875   , 0.01875   , 0.44375   ],
        [0.01875   , 0.01875   , 0.01875   , 0.01875   , 0.30208333,
         0.01875   , 0.01875   , 0.44375   ],
        [0.01875   , 0.01875   , 0.01875   , 0.01875   , 0.30208333,
         0.86875   , 0.44375   , 0.01875   ]]))

In [118]:
final_init_I = [1,0,0,0,0,0,0,0]
for i in range(1000):
    final_init_I = np.dot(G,final_init_I)
    final_init_I /= np.linalg.norm(final_init_I,1)
final_init_I

array([0.01875   , 0.05715045, 0.02671875, 0.06732788, 0.12848733,
       0.2056777 , 0.18660147, 0.30928641])