In [39]:
import numpy as np
import math

In [11]:
mat_1 = np.arange(3)
mat_2 = np.arange(3,6)
print(mat_1)
print(mat_2)

[0 1 2]
[3 4 5]


In [9]:
mat_1*mat_2

array([ 0,  4, 10])

In [10]:
np.dot(mat_1,mat_2)

14

In [12]:
np.cross(mat_1,mat_2)

array([-3,  6, -3])

In [13]:
mat_1 = np.arange(9).reshape([3,3])
mat_2 = np.arange(9,18).reshape([3,3])
print(mat_1)
print(mat_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [14]:
mat_1*mat_2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [16]:
np.dot(mat_1, mat_2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [17]:
np.cross(mat_1, mat_2)

array([[-9, 18, -9],
       [-9, 18, -9],
       [-9, 18, -9]])

In [74]:
r1,th1 = 8,20
r2,th2 = 5,240

In [86]:
r1,th1 = 7,160
r2,th2 = 9,20
print(round((r1 * math.cos(np.radians(th1))) + (r2*math.cos(np.radians(th2))),2),round((r1 * math.sin(np.radians(th1))) + (r2*math.sin(np.radians(th2))),2))

1.88 5.47


In [76]:
round((r1 * math.sin(np.radians(th1))) + (r2*math.sin(np.radians(th2))),2)

-1.59

In [55]:
(8*math.sin(np.radians(140)))

5.142300877492316