In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
path = r"C:\Users\eakhumb\Downloads\Queue Report - GF00004_WPA JR - 2020-02-17 08-37.csv"

In [3]:
data = pd.read_csv(path)

In [5]:
data["Loaded"] = pd.to_datetime(data["Loaded"])

In [14]:
data["MMDD"] = (data["Loaded"].dt.month*100) + data["Loaded"].dt.day

In [41]:
AHT = data.groupby("MMDD")["Worktime"].mean().reset_index()

In [26]:
data["Completed?"] = data["Completed"].apply(lambda x: 0 if pd.isnull(x) else 1)

In [42]:
count = data.groupby(["MMDD", "Completed?"]).size().unstack()

In [43]:
AHT = pd.merge(AHT, data.groupby(["MMDD", "Completed?"])["Worktime"].mean().unstack(), on="MMDD")

In [36]:
data[data["MMDD"]==210]["ExceptionReason"].unique()

array(['System Exception : Previous Status Should be HMM.',
       'System Exception : Unable to click filter option link',
       "Internal : Failed to perform step 1 in Read Stage 'Read Current Status' on page 'WPA JR_Pending GLT' - No element matched the query terms",
       nan,
       'System Exception : Unable to Find Final Click Send to Approver Button on HMM',
       "Internal : Failed to perform step 1 in Navigate Stage 'Send to Approver' on page 'WPA JR_HMM' - Old format or invalid type library. (Exception from HRESULT: 0x80028019 (TYPE_E_UNSUPFORMAT))"],
      dtype=object)

In [44]:
pd.merge(AHT, count, on="MMDD")

MMDD    Worktime         0_x         1_x  0_y  1_y
0    108  156.880383   91.695652  164.940860   23  186
1    109  119.541353   10.444444  147.330189   27  106
2    110   65.076923   35.287263  153.016000  369  125
3    113  135.692884   86.245614  149.114286   57  210
4    114  138.785714   94.631579  143.525424   19  177
5    115  128.588832   83.878788  137.585366   33  164
6    116  163.849462  100.764706  170.195266   17  169
7    117  150.813793   85.363636  162.520325   22  123
8    120  187.567416  111.695652  198.825806   23  155
9    122  122.239316   55.074074  157.797386   81  153
10   123  183.259259   71.875000  195.465753    8   73
11   124  117.105042   77.158730  162.044643  126  112
12   127  154.170886  112.696203  195.645570   79   79
13   128  138.193443   85.566038  166.226131  106  199
14   129  161.162562   79.727273  171.060773   22  181
15   130  110.276471   35.838710  200.181818   93   77
16   131  205.740506  107.250000  208.298701    4  154
17   203  235.961538  413.947368  205.495495   19  111
18   204  162.330827  131.830601  229.578313  183   83
19   205  216.915789  210.200000  217.288889    5   90
20   206  354.325581  236.500000  360.073171    2   41
21   210  228.753731  179.769231  248.863158   39   95

In [7]:
x = np.array([[[1, 1, 1], [1, 1, 1], [1, 1, 1]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]]])
x

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [28]:
pad=1
np.pad(x, ((0,0), (pad,pad), (pad,pad)), mode='constant', constant_values = (0,0))

array([[[0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0]]])

In [29]:
a_slice_prev = np.random.randn(4, 4, 3)
W = np.random.randn(4, 4, 3)

In [33]:
-0.07433922 * -0.12876091

0.0095719856158902

In [37]:
x

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [48]:
x=10
x+=20
x

30